//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LineNotify.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Examiners = new HashSet<Examiners>();
        }
    
        public int id { get; set; }
        public int patient_id { get; set; }
        public string patient_name { get; set; }
        public string gender { get; set; }
        public int test_id { get; set; }
        public string test_name { get; set; }
        public System.DateTime date { get; set; }
        public string doctor_name { get; set; }
        public System.DateTime birth_date { get; set; }
        public string blood { get; set; }
        public string diagnosis { get; set; }
        public string id_card { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examiners> Examiners { get; set; }
    }
}
